services:
  zipkin:
    image: openzipkin/zipkin:3.3.0
    ports:
    - 9411:9411
  cambioservice-db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cambioservice
      TZ: America/Sao_Paulo
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - app-network
  bookservice-db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: bookservice
      TZ: America/Sao_Paulo
    ports:
      - 5433:5432
    expose:
      - 5433
    networks:
      - app-network
networks:
  app-network:
    driver: bridge