eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
management:
    tracing:
        sampling:
            probability: 1.0
server:
    port: 8000
spring:
    application:
        name: cambio-service
    datasource:
        url: jdbc:postgresql://localhost:5432/cambioservice
        username: postgres
        password: admin123
    flyway:
        locations: classpath:/db/migrations
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
springdoc:
    show-actuator: true
    api-docs:
        path: cambio-service/v3/api-docs