management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
    port: 8888
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                native:
                    searchLocations: classpath:/greeting-service/
    profiles:
        active:
            - native
