eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8100
spring:
    application:
        name: book-service
    datasource:
        url: jdbc:postgresql://localhost:5433/bookservice
        username: postgres
        password: admin123
    flyway:
        locations: classpath:/db/migrations
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
springdoc:
    show-actuator: true
    api-docs:
        path: book-service/v3/api-docs
